USE [master]
GO

-- Password=vidly
CREATE LOGIN [vidly] WITH PASSWORD=N'lXjOuWh1cIRAEWkqLUKDVZTQPKKzAfpziWX4zcXK/28=', DEFAULT_DATABASE=[Vidly], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON
GO

GRANT CREATE ANY DATABASE TO [vidly]
GO